# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty


# Setup
title:            Ehsan Motevalli
tagline:          'CV'
description:      ''
url:              https://jammt-vestas.github.io/


highlighter:      rouge
markdown:         kramdown


paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Jammt-Vestas/jammt-vestas.github.io
